language: python
python:
- '2.7'
- '3.4'
install: pip install -r pytx/requirements.txt
env:
- TEST_DIR=pytx
before_install:
- pip install tox
script: cd $TEST_DIR && make test
deploy:
  provider: pypi
  user: mgoffin
  password:
    secure: GIqJaQRlk5zCYIsWIX+2AjOrEPMz3YPVN4REUBlJbeLeJTTCUdrnlpfWdJmIaDA83wu7Q8gGfDmlyyyq+UY5EaQ54mHwbxseFxdG7zm/F3jrrD73lwgbq5ZgmdfoSBs0lJ++4o3c9mD4b0agK1me/WKlkcRZDo67gKlLqa8cYD7YVcYldWQcaM1xUvOBL+z7MiV1h4MkOp2nI51dPDfUvoLscKavl/rCxwt0kbTfLlJj02tUfYQfwK+eWqsLPtM8QdpHObWXpnV5K/u12qD3oUyy4ZVkJtJ93tC27rVODI9q1pIMH62oKVrU5WqPI575jX9kLeMlgEYboevrseKZoh3myO14MxAYpc1dEoNbSe4yi8FfkcTVxdlhRtelE3y2zMsYSlS3aS0KjpASMJE4r+Hdtnilw8d8xzjv7pDrL24sLxOQ4dKHK9WGHsUhAuj6+e82saLVo9slEppSALY2y+faWEiwAIRoh8q420KdEiS6kVMgrz8NGAuJVMK7kN/yp5qyzJfUeYNHI0wx2zKPb6fTlLXSE+o3mXPh6BnjHcuGv85Dj76NyOUlgClCdAXVszTNvz+M3pbQT7PeCfq6005qs+VuNc3dpTkrZY+7+h0lSHVIr4jozxAczwRBTli8LzaWZxCTb83/PLoxS4scnP6z8YhAVt27bQioC78rT0c=
  on:
    tags: true
    repo: facebook/ThreatExchange
